# Generated by Django 2.2.3 on 2019-07-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('nid', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('m', 'MALE'), ('f', 'FEMALE')], max_length=1)),
                ('package', models.CharField(choices=[('anc', 'Anti Natal Check UP'), ('ahp', 'Adult Health Package'), ('adc', 'After Delivery Check Up')], max_length=2)),
            ],
        ),
    ]
