# Generated by Django 2.2.3 on 2019-07-18 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Villager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='villager',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/villager/profile_pic/'),
            preserve_default=False,
        ),
    ]
