# Generated by Django 2.2.3 on 2019-07-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Villager', '0002_villager_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villager',
            name='package',
            field=models.CharField(choices=[('anc', 'Anti Natal Check UP'), ('ahp', 'Adult Health Package'), ('adc', 'After Delivery Check Up')], max_length=3),
        ),
    ]
