# Generated by Django 2.2.3 on 2019-07-18 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Villager', '0003_auto_20190719_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='villager',
            name='reg_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Registration Number'),
            preserve_default=False,
        ),
    ]
