# Generated by Django 2.2.3 on 2019-07-18 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Villager', '0004_villager_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='villager',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='villager',
            name='nid',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='villager',
            name='reg_no',
            field=models.CharField(max_length=30, unique=True, verbose_name='Registration Number'),
        ),
    ]
