# Generated by Django 2.2.3 on 2019-07-18 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Villager', '0005_auto_20190719_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='villager',
            name='follow_up_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='villager',
            name='next_follow_up_date',
            field=models.DateField(null=True),
        ),
    ]
