# Generated by Django 2.2.3 on 2019-07-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Villager', '0006_auto_20190719_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villager',
            name='next_follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
