# Generated by Django 2.2.3 on 2019-07-19 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Villager', '0008_remark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remark',
            options={'ordering': ['-id']},
        ),
    ]
